export const navItems = [
    {
        title:"Dashboard",
        icon:"/assets/Group.png",
        path:"/",
    },
    {
        title:"Lawyers",
        icon:"/assets/lawyer.png",
        path:"/lawyer",
    },
    {
        title:"Total Users",
        icon:"/assets/totalUser.png",
        path:"/total-users",
    },
    {
        title:"Cases",
        icon:"/assets/cases.png",
        path:"/",
    },
    {
        title:"Notification",
        icon:"/assets/notification.png",
        path:"/",
    },
    {
        title:"Meetings",
        icon:"/assets/meeting.png",
        path:"/",
    },
    {
        title:"Bookings",
        icon:"/assets/booking.png",
        path:"/",
    },
    {
        title:"Services",
        icon:"/assets/services.png",
        path:"/",
    },
    {
        title:"Banners",
        icon:"/assets/banners.png",
        path:"/banner",
    },
    {
        title:"AllFiles",
        icon:"/assets/allfiels.png",
        path:"/",
    },
    {
        title:"To-Do-List",
        icon:"/assets/todolist.png",
        path:"/",
    },
    {
        title:"Permissions",
        icon:"/assets/Group.png",
        path:"/",
    },
    {
        title:"Messages",
        icon:"/assets/messages.png",
        path:"/",
    },

]